# Generated by Django 6.0.1 on 2026-01-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bullet_points', models.TextField(blank=True)),
                ('product_type_id', models.IntegerField(blank=True, null=True)),
                ('product_length', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
